# Generated by Django 5.1.6 on 2025-07-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_riskprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskprofile',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='tolerance',
            field=models.IntegerField(null=True),
        ),
    ]
