# Generated by Django 5.1.6 on 2025-07-08 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_riskprofile_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliomodel',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.portfoliomodel'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
