# Generated by Django 5.1.6 on 2025-07-11 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_portfoliomodel_user_userprofile_portfolio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(unique=True)),
                ('question_type', models.CharField(choices=[('Tolerance', 'Risk Tolerance'), ('Capacity', 'Risk Capacity')], max_length=20)),
                ('question_text', models.TextField()),
                ('question_weight', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['question_id'],
            },
        ),
        migrations.CreateModel(
            name='RiskAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.IntegerField(unique=True)),
                ('answer_text', models.CharField(max_length=200)),
                ('answer_value', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='main.riskquestion')),
            ],
            options={
                'ordering': ['answer_value'],
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='main.riskprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.riskquestion')),
                ('selected_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.riskanswer')),
            ],
            options={
                'unique_together': {('assessment', 'question')},
            },
        ),
    ]
