# Generated by Django 5.1.6 on 2025-07-11 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_riskquestion_riskanswer_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskprofile',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='riskprofile',
            name='tolerance',
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='capacity_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='tolerance_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
