# Generated by Django 5.1.6 on 2025-07-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_riskprofile_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationmodel',
            name='percentage',
            field=models.FloatField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='allocationmodel',
            name='ticker',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
