# Generated by Django 5.1.5 on 2025-07-23 18:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_allocationmodel_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='riskanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_answer',
        ),
        migrations.RemoveField(
            model_name='riskprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='balance',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='investment_experience',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('bond', 'Bond'), ('etf', 'ETF'), ('cash', 'Cash')], max_length=20)),
                ('shares', models.DecimalField(decimal_places=4, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_type', models.CharField(choices=[('conservative', 'Conservative'), ('balanced', 'Balanced'), ('growth', 'Growth'), ('aggressive', 'Aggressive Growth')], max_length=20)),
                ('stocks_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bonds_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('etfs_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cash_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_tolerance', models.CharField(choices=[('conservative', 'Conservative'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], max_length=20)),
                ('time_horizon', models.IntegerField(help_text='Investment time horizon in years')),
                ('financial_goals', models.TextField()),
                ('risk_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AllocationModel',
        ),
        migrations.DeleteModel(
            name='PortfolioModel',
        ),
        migrations.DeleteModel(
            name='RiskAnswer',
        ),
        migrations.DeleteModel(
            name='RiskProfile',
        ),
        migrations.DeleteModel(
            name='RiskQuestion',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
